Algoritmo "EXERCICIOenquantoD"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Demonstrar todos os números ímpares até o número 20
// Autor(a)    : Guilherme Caetano
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto contador<=20 faca
se contador mod 2 = 1 entao
Escreval(contador)
fimse
contador<-contador+1
fimenquanto

Fimalgoritmo