Algoritmo "Temporizador"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Cronômetro
// Autor(a)    : Guilherme Caetano
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis
contadora,contadora1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contadora de 59 ate 0 passo -1 faca
para contadora1 de 59 ate 0 passo -1 faca
Escreval(contadora, " :", contadora1)

timer 500

fimpara
fimpara


Fimalgoritmo