Algoritmo "Área do triângulo"
//
//
// Descrição   : Área do triângulo
// Autor(a)    : Jailson
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
base:real
altura:real
triangulo:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Escreva a base do triângulo:")
leia (base)
escreval("Escreva a altura do triângulo:")
leia (altura)
triangulo<-(base*altura)/2
escreva("A área do triângulo é:",triangulo)

Fimalgoritmo