Algoritmo "circulo"
// Disciplina  : Lógica de programação
// Professor   : Obama
// Descrição   : Algoritimo que cálcula a área de um círculo.
// Autor(a)    : Guilherme Caetano
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis 
raio:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva o raio do círculo:")
leia (raio)
area<-PI*(raio^2)
escreva("A área do círculo é:",area)
Fimalgoritmo