Algoritmo "epositivo"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Guilherme Caetano
// Data atual  : 24/03/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um valor :")
   Leia(numero)
   se (numero>=0) entao
      Escreval("Valor digitado é positivo")
   senao
      Escreval("Valor digitado é negativo")
   fimse
Fimalgoritmo