Algoritmo "distributiva"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Aplicar a propriedade de distributiva
// Autor(a)    : Guilherme Caetano
// Data atual  : 24/03/2023
Var
// Seção de Declarações das variáveis
numero1:inteiro
numero2:inteiro
numero3:inteiro
numero4:inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite o 1º número:")
leia(numero1)
escreva ("Digite o 2º número:")
leia(numero2)
escreva ("Digite o 3º número:")
leia(numero3)
escreva ("Digite o 4º número:")
leia(numero4)

escreval ("O valor da soma do 1º número com o 2º é de:", numero1+numero2)
escreval ("O valor da soma do 1º número com o 3º é de:", numero1+numero3)
escreval ("O valor da soma do 1º número com o 4º é de:", numero1+numero4)
escreval ("O valor da soma do 2º número com o 3º é de:", numero2+numero3)
escreval ("O valor da soma do 2º número com o 4º é de:", numero2+numero4)
escreval ("O valor da soma do 3º número com o 4º é de:", numero3+numero4)
escreval ("O valor da multiplicação do 1º número com o 2º é de:", numero1*numero2)
escreval ("O valor da multiplicação do 1º número com o 3º é de:", numero1*numero3)
escreval ("O valor da multiplicação do 1º número com o 4º é de:", numero1*numero4)
escreval ("O valor da multiplicação do 2º número com o 3º é de:", numero2*numero3)
escreval ("O valor da multiplicação do 2º número com o 4º é de:", numero2*numero4)
escreval ("O valor da multiplicação do 3º número com o 4º é de:", numero3*numero4)



Fimalgoritmo