Algoritmo "converreal"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Conversão de Real para dolar
// Data atual  : 24/03/2023
Var
// Seção de Declarações das variáveis
cotacaoDolar:real
valorReal:real
conversaoDolar:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor da cotação em Dolar: ")
leia(cotacaoDolar)
escreva("Digite o valor em Real: ")
leia(valorReal)

conversaoDolar <- valorReal/cotacaoDolar
escreva(valorReal, " em dolar é igual a : ", conversaoDolar)


Fimalgoritmo

