Algoritmo "calculando"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : O resultado do quadrado da diferença do primeiro valor pelo segundo.
// Autor(a)    : Guilherme Caetano
// Data atual  : 24/03/2023
Var
// Seção de Declarações das variáveis
A, B: inteiro
resultado: inteiro

Inicio
Escreval("Digite o valor de A:")
leia (A)
Escreval("Digite o valor de B:")
leia (B)
resultado<-(A-B)*(A-B)
Escreval("O resultado do quadrado da diferença do primeiro valor pelo segundo é:", resultado)

Fimalgoritmo