Algoritmo "calculoFahrenheit"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Calcular a temperatura em Fahrenheit
// Autor(a)    : Guilherme Caetano
// Data atual  : 23/03/2023


Var
// Seção de Declarações das variáveis
temperaturaFahrenheit, temperaturaCelcius: real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a temperatura em  Celcius:")
leia (temperaturaCelcius)

temperaturaFahrenheit<-(9*temperaturaCelcius+160)/5
escreval ("A temperatura em Fahrenheit é:",temperaturaFahrenheit)
Fimalgoritmo