Algoritmo "calculoCelcius"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Calcular a temperatura em Celcius
// Autor(a)    : Guilherme Caetano
// Data atual  : 23/03/2023


Var
// Seção de Declarações das variáveis
temperaturaFahrenheit, temperaturaCelcius: real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a temperatura em Fahrenheit:")
leia (temperaturaFahrenheit)

temperaturaCelcius<-((5*temperaturaFahrenheit)-(32*5))/9
escreval ("A temperatura em Celcius é:",temperaturaCelcius)
Fimalgoritmo