Algoritmo "EXERCICIOPARAH"
// Disciplina  : Lógica de programação
// Professor   : Jailson 
// Descrição   : Celcius para Fahrenheit
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2023
Var
grauCelsius:inteiro
grauFahrenheit: real

Inicio
Para grauCelsius de 10 ate 100 passo 10 faca
grauFahrenheit<- (9 * grauCelsius +160)/5
Escreval(grauCelsius, " graus Celsius é igual a ", grauFahrenheit, " graus Fahrenheit")
FimPara
FimAlgoritmo